tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "surface-tint": "#9e2c74",
                "surface-container-high": "#e6e8ea",
                "on-secondary-fixed-variant": "#004085",
                "tertiary-fixed": "#d0d8ff",
                "error": "#ba1a1a",
                "on-surface": "#191c1e",
                "on-primary-fixed-variant": "#7a1a55",
                "inverse-surface": "#2d3133",
                "on-primary-fixed": "#ffffff",
                "secondary-fixed-dim": "#b6c4ff",
                "on-tertiary-fixed-variant": "#000045",
                "surface-container-low": "#f2f4f6",
                "primary-fixed": "#000065",
                "surface-variant": "#e0e3e5",
                "on-secondary-fixed": "#00164e",
                "on-error-container": "#93000a",
                "surface-container-lowest": "#ffffff",
                "on-primary-container": "#ffffff",
                "on-secondary-container": "#ffffff",
                "primary-container": "#000065",
                "surface-bright": "#f7f9fb",
                "on-error": "#ffffff",
                "background": "#f7f9fb",
                "outline-variant": "#c4c6cf",
                "primary": "#9e2c74",
                "on-primary": "#ffffff",
                "surface": "#f7f9fb",
                "on-surface-variant": "#3f4946",
                "on-tertiary": "#ffffff",
                "secondary": "#0056b3",
                "surface-container": "#eceef0",
                "surface-dim": "#d8dadc",
                "on-tertiary-fixed": "#000033",
                "inverse-on-surface": "#eff1f3",
                "secondary-fixed": "#dce1ff",
                "outline": "#6f7976",
                "secondary-container": "#6780e1",
                "on-background": "#191c1e",
                "tertiary": "#000045",
                "on-tertiary-container": "#ffffff",
                "on-secondary": "#ffffff",
                "primary-fixed-dim": "#000045",
                "tertiary-fixed-dim": "#6780e1",
                "error-container": "#ffdad6",
                "inverse-primary": "#fce8f3",
                "surface-container-highest": "#e0e3e5",
                "tertiary-container": "#000045"
            },
            fontFamily: {
                "headline": ["Public Sans"],
                "body": ["Public Sans"],
                "label": ["Public Sans"]
            },
            borderRadius: { "DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px" },
        },
    },
};